### ISSUE TITLE
Global 'jpeg' variable lost in latest NPM build.

### ISSUE THREAD

**Issue by create3000** [rii-mango/JPEGLosslessDecoderJS#16]
Installed latest 2.0.5 version from NPM and missed 'jpeg' variable.

```html
<script src="../node_modules/jpeg-lossless-decoder-js/release/current/lossless.js"></script>
<script>
const decoder = new jpeg .lossless .Decoder ();
// oops no 'jpeg' variable
</script>
```

**Comment by rii-mango** [comment]
Try it like this:
`const jpeg = require('jpeg-lossless-decoder-js');
var decoder = new jpeg.lossless.Decoder();`

**Comment by create3000** [comment]
I'm working with JavaScript module system (*.mjs) and import statement. This means require is no option.

**Comment by rii-mango** [comment]
What import statement are you using?

**Comment by create3000** [comment]
Normal JS module system.

```js
// For instance
import X3DInfoArray from "../Base/X3DInfoArray.js";
```

The project is bundled with [Webpack](https://webpack.js.org) which works with version 2.0.4.

If there would be a *.mjs version of the bundled library, as some repros do, this would be maybe the solution.

**Comment by rii-mango** [comment]
Does this work?
```js
import lossless from "../path/to/lossless.js"
const decoder = new lossless.Decoder();
```

**Comment by create3000** [comment]
This does not work.
There must be a top-level `export` statement in the file, which isn't.

```js
export lossless;
```

**Comment by rii-mango** [comment]
How about the version from today?

**Comment by create3000** [comment]
No luck.

When I bundle the project with Webpack, I get the following error:

```console
WARNING in ./node_modules/jpeg-lossless-decoder-js/release/current/lossless.js 4:75-82
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

This will happen if you do something like this `require ("foo" + somevar)`

**Comment by create3000** [comment]
Can it be that the wrapper stuff has changed, and then the `jpeg` var is not accessible?

**Comment by create3000** [comment]
Version 2.0.7 works again. Thank you very much!
