### ISSUE TITLE
Version 2.1.0 is broken version 2.0.7 works

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [rii-mango/JPEGLosslessDecoderJS#18]
```
node:internal/modules/cjs/loader:444
      throw err;
      ^

Error: Cannot find module '/usr/src/app/node_modules/jpeg-lossless-decoder-js/build/main.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:436:19)
    at Module._findPath (node:internal/modules/cjs/loader:678:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/usr/src/app/node_modules/daikon/src/image.js:14:48)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/usr/src/app/node_modules/jpeg-lossless-decoder-js/package.json',
  requestPath: 'jpeg-lossless-decoder-js'
}
```

**Comment by create3000** [comment]
README.md still mentions that there is a release folder: https://github.com/rii-mango/JPEGLosslessDecoderJS#install

But following the link https://github.com/rii-mango/JPEGLosslessDecoderJS/tree/master/release result in a 404.

**Comment by tudor33sud** [comment]
encountered the same issue while using daikon. Is there any plan to fix it ? Thanks !

**Comment by rii-mango** [comment]
@jens-ox The [PR](https://github.com/rii-mango/JPEGLosslessDecoderJS/commit/f158b1e3353d3f65e6f311d527a974fdee80ea70) to use TypeScript removes the release folder.  Browserify and/or esbuild used to create lossless.js and lossless-min.js.

What are the intended release files in TypeScript?

I see build/main.cjs, main.map.cjs and main.d.cts.  Is there some way to create lossless.js and lossless-min.js from these?

**Comment by rii-mango** [comment]
@MichaelLeeHobbs @create3000  @tudor33sud How does version 2.1.1 work for you?

**Comment by create3000** [comment]
Message in Safari:

![error](https://github.com/rii-mango/JPEGLosslessDecoderJS/assets/2930196/df17f421-ff6c-414b-beac-042d25d64bec)

**Comment by rii-mango** [comment]
[lossless.js:33](https://github.com/rii-mango/JPEGLosslessDecoderJS/blob/38d054c183a1019492fdb1b0665297eb589109a4/release/lossless.js#L33) module.exports = __toCommonJS(main_exports);

@jens-ox Should this be using 'export' instead of 'module.exports'?
(Apologies if this isn't helpful- it's from a brief search that showed topics like "What's the difference between CommonJS and ES modules?".  Thanks for submitting PR19.)

**Comment by jens-ox** [comment]
I'll fix it in the morning :)

**Comment by tudor33sud** [comment]
@rii-mango  for us everything s ok now, however I am using the package in Node JS environment, not sure if it makes any difference. 👌

**Comment by jens-ox** [comment]
@create3000 @rii-mango I've raised #20, which ensures that the library can be used in all environments.

**Comment by create3000** [comment]
I would very much appreciate an ES Module version.

**Comment by rii-mango** [comment]
@create3000 how does version 2.1.2 work for you?

**Comment by create3000** [comment]
Tested now latest version with:
```js
import { Decoder } from "../../../../node_modules/jpeg-lossless-decoder-js/release/lossless.js";
```
and could successfully import the Decoder. I still had no time to test the Decoder itself, but I hope there are no changes to the interface. 

I also run WebPak to package the project, which also works fine again.

Thank you very much for your efforts.

**Comment by jens-ox** [comment]
@create3000 there should be no changes to the interface. Just out of curiosity, how are you ending up with such a convoluted import path? You should at least be able to import it like this:

```js
import { Decoder } from "../../../../node_modules/jpeg-lossless-decoder-js"
```

**Comment by create3000** [comment]
Don’t worry about that. It is the path of a file of the unpackaged sources, which I have to test in a web browser, and a web browser does not know much about package.json and node_modules folder.
