### ISSUE TITLE
'Not a JPEG file' thrown for .57 image

### ISSUE THREAD

**Issue by chafey** [rii-mango/JPEGLosslessDecoderJS#2]
This .57 image threw 'Not a JPEG file':

http://barre.nom.fr/medical/samples/#MR-MONO2-12-shoulder

Load fine in Osirix.  Any ideas?

**Comment by rii-mango** [comment]
If you were using the included tests/driver.js, then you'll need to change the offset and length of the JPEG data block.  I used DICOM files as tests, since I think it's only DICOM that uses this type of compression, but there is no DICOM reader in the code -- so you'll have to tell it where in the DICOM file the JPEG data starts.  Here's a version of tests/driver.js that uses the file you linked to:

``` JavaScript
/*jslint browser: true, node: true */
/*global require, module */

"use strict";

var jpeg = require('../src/main.js');


var fs = require('fs');


function toArrayBuffer(buffer) {
    var ab, view, i;

    ab = new ArrayBuffer(buffer.length);
    view = new Uint8Array(ab);
    for (i = 0; i < buffer.length; i += 1) {
        view[i] = buffer[i];
    }
    return ab;
}

var jpegDataOffset = 1596;//1654;
var jpegDataSize = 718923;//143474;

var buf = new Buffer(jpegDataSize);

var fd = fs.openSync('./tests/data/MR-MONO2-12-shoulder', "r");
fs.readSync(fd, buf, 0, buf.length, jpegDataOffset);
var data = toArrayBuffer(buf);
var decoder = new jpeg.lossless.Decoder(data);
var output = decoder.decode();

var assert = require("assert");
describe('JPEGLosslessDecoderJS', function () {
    it('dimX should equal 1024', function () {
        assert.equal(1024, decoder.frame.dimX);
    });

    it('dimY should equal 1024', function () {
        assert.equal(1024, decoder.frame.dimY);
    });

    it('number of components should be 1', function () {
        assert.equal(1, decoder.frame.numComp);
    });

    it('decompressed size should be 2097152', function () {
        assert.equal(2097152, output.byteLength);
    });
});
```

**Comment by chafey** [comment]
OK I see the problem - I am using dicomParser to extract the frame and it has an optimization in the case of a single fragment that returns the fragment as a Uint8Array view (offset + length) on the underlying ArrayBuffer (which covers the entire DICOM P10 instance).  I can workaround this by removing the optimization and making a copy of the buffer, but it would be nice if this library could support a copyless buffer - perhaps accept Uint8Array or the ArrayBuffer with an offset and length

**Comment by rii-mango** [comment]
Ok, see the new usage:

```
var decoder = new jpeg.lossless.Decoder();
var decompressedData = decoder.decode(buffer [, offset [, length [, numBytes]]]);

// {ArrayBuffer} buffer
// {Number} offset offset into buffer (default = 0)
// {Number} length length of buffer (default = end of JPEG block)
// {Number} number of bytes per output unit (default = 2)
```

Let me know if this doesn't work for you.
