### ISSUE TITLE
Support RGB data

### ISSUE THREAD

**Issue by rii-mango** [rii-mango/JPEGLosslessDecoderJS#4]
Currently, this decoder collapses RGB data into single component intensity data.  The original code supported returning RGB data, so it shouldn't be hard to add this...

**Comment by leonardorame** [comment]
Hi, I think I stumbled upon the same issue with Cornerstone, I posted an issue there: https://github.com/chafey/cornerstoneWADOImageLoader/issues/18 can you read it and comment?.

**Comment by rii-mango** [comment]
Ok, version 1.2 now supports RGB data.  Please give it a try: chafey/cornerstoneWADOImageLoader#18
