### ISSUE TITLE
Unable to parse the attached JPEG Lossless file correctly

### ISSUE THREAD

**Issue by lakeeast** [rii-mango/JPEGLosslessDecoderJS#5]
I tried to use your code to open a JPEG Lossless file at https://www.dropbox.com/s/0u08ejwn1hxrhku/002850d9.dcm?dl=0, but the code didn't parse it correctly (it didn't report any error either). Interestingly, pixel #0 to #511 are all correct: but pixel #512 and afterwards are incorrect. The correct value for pixel #512 should be 972, but we got 34711 instead.

**Comment by rii-mango** [comment]
Yes, definitely a bug.  Thanks for reporting this.  I'm looking into it...

**Comment by rii-mango** [comment]
Should be fixed now.

**Comment by lakeeast** [comment]
Thanks! It worked!
