### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by medihack** [rii-mango/JPEGLosslessDecoderJS#6]
Thanks a lot for you excellent work! Would it be possible to publish it as a package on NPM?

**Comment by rii-mango** [comment]
Done! https://www.npmjs.com/package/jpeg-lossless-decoder-js

I'm not so familiar with NPM, so please let me know if something doesn't look right.

**Comment by medihack** [comment]
Thank you. Looks fine :-)

You could also add something like this to the Readme.md (even if it is obvious for most users):

```
###Install
Get a packaged source file:

* [lossless.js](https://raw.githubusercontent.com/rii-mango/JPEGLosslessDecoderJS/master/release/current/lossless.js)
* [lossless-min.js](https://raw.githubusercontent.com/rii-mango/JPEGLosslessDecoderJS/master/release/current/lossless-min.js)

Or install via [NPM](https://www.npmjs.com/):

> npm install JPEGLosslessDecoderJS

Or install via [Bower](http://bower.io/):

> bower install JPEGLosslessDecoderJS
```

Thanks again for this nice decoder!
